#'''Parameters'''#

# --- general --- #

# --- trim_reads --- #

trim_reads_mem_mb: 40000
trim_reads_threads: 4

# --- filter_lowqual_reads --- #

filter_lowqual_reads_mem_mb: 40000
quality: 10

# --- filter_host_reads --- #

host_genome: /home/mike/Documents/grad_school/genomes/hg38.fa
filter_host_reads_mem_mb: 40000
filter_host_reads_threads: 10

# --- statistics --- #

count_reads_mem_mb: 40000
