#'''Parameters'''#

# --- general --- #

fastqc_threads: 40

# --- trim_reads --- #

trim_reads_mem_mb: 40000
trim_reads_threads: 40

# --- filter_lowqual_reads --- #

filter_lowqual_reads_mem_mb: 40000 
quality: 8

# --- filter_host_reads --- #

use_host_filter: False
host_genome: /home/bet4006/camp/GRCh38_28122022/GRCh38.fna
filter_host_reads_mem_mb: 40000 
filter_host_reads_threads: 40

# --- statistics --- #

count_reads_mem_mb: 40000 
