#'''Parameters'''#

# --- general --- #

fastqc_threads: 40

# --- trim_reads --- #

trim_reads_mem_mb: 40000
trim_reads_threads: 40

# --- filter_lowqual_reads --- #

filter_lowqual_reads_mem_mb: 40000 
quality: 0

# --- filter_host_reads --- #

host_genome: <INSERT_PATH_TO_REFERENCE>
filter_host_reads_mem_mb: 40000 
filter_host_reads_threads: 40

# --- statistics --- #

count_reads_mem_mb: 40000 
